@InventoryWorker_HostAddress = http://localhost:5080

GET {{InventoryWorker_HostAddress}}/api/stock
Accept: application/json

###

GET {{InventoryWorker_HostAddress}}/api/stock/ABC-01
Accept: application/json

###
